name: simple_cubit_app
description: A simple Flutter application using the Cubit pattern for state management, consisting of a login screen and a home screen.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0

flutter:
  uses-material-design: true